# The picker catalog is derived from the shipped scripts, not maintained by hand.
# A script is directly runnable only when it exports the conventional main node;
# helper modules (such as radial.mr) remain import-only and are omitted.
set(ENGINE_SIM_GENERATED_INCLUDE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/generated")
file(MAKE_DIRECTORY "${ENGINE_SIM_GENERATED_INCLUDE_DIRECTORY}")
set(ENGINE_SIM_ENGINE_CATALOG_INCLUDE
    "${ENGINE_SIM_GENERATED_INCLUDE_DIRECTORY}/engine_catalog_paths.inc")

file(GLOB_RECURSE ENGINE_SIM_ENGINE_SCRIPT_FILES CONFIGURE_DEPENDS
    RELATIVE "${CMAKE_CURRENT_SOURCE_DIR}/assets"
    "${CMAKE_CURRENT_SOURCE_DIR}/assets/engines/*.mr")
list(SORT ENGINE_SIM_ENGINE_SCRIPT_FILES)

set(ENGINE_SIM_ENGINE_CATALOG_CONTENT "// Generated by CMake from assets/engines. Do not edit.\n")
foreach(engine_script IN LISTS ENGINE_SIM_ENGINE_SCRIPT_FILES)
    file(READ "${CMAKE_CURRENT_SOURCE_DIR}/assets/${engine_script}" engine_script_contents)
    if(engine_script_contents MATCHES "public[ \t\r\n]+node[ \t\r\n]+main([ \t\r\n\\{]|$)")
        string(APPEND ENGINE_SIM_ENGINE_CATALOG_CONTENT "    \"${engine_script}\",\n")
    endif()
endforeach()
file(WRITE "${ENGINE_SIM_ENGINE_CATALOG_INCLUDE}" "${ENGINE_SIM_ENGINE_CATALOG_CONTENT}")
